"""
PentestBot v2 — Git Exposure Stage
Wrapper for the custom git-explosure.sh script.
"""

import asyncio
from pathlib import Path
from pipeline.base_stage import BaseStage

class GitExposureStage(BaseStage):
    NAME = "GitExposure"

    async def run(self) -> None:
        subdomains = self.ctx.get("subdomains", [])
        if not subdomains:
            # Fallback to target if no subdomains found
            subdomains = [self.target]

        # Ensure the script is executable
        script_path = Path("scripts/git-explosure.sh")
        # Note: We run it from the backend root where scripts/ is located
        
        self.log.info(f"[{self.NAME}] Running Git exposure check on {len(subdomains)} targets...")
        
        # We will run the script but we can also optimize by passing our subdomains
        # However, to respect your script's logic, we'll run it as intended:
        # ./scripts/git-explosure.sh <domain>
        
        cmd = ["bash", "scripts/git-explosure.sh", self.target]
        
        # We use our runner to capture output for Raw Data Preservation
        result = await self.runner.run(cmd, timeout=600)
        self.log_result(result)

        if not result.success:
            self.add_tool_error(f"Script failed with exit code {result.returncode}")
            return

        # Parse results from the file generated by the script
        # The script saves to: ${DOMAIN}-git_exposure_results.txt
        exposure_file = self.work_dir / f"{self.target}-git_exposure_results.txt"
        
        findings = []
        if exposure_file.exists():
            lines = self.read_lines(exposure_file)
            for line in lines:
                # httpx output usually: http://sub.domain.com/.git/HEAD [200] [123] [Title]
                findings.append(line)
        
        self.ctx["git_exposure_findings"] = findings
        self.log.info(f"[{self.NAME}] Found {len(findings)} potential Git exposures.")
